games:
  write_it_down:
    # seconds between logograms or syllabograms
    secs_between_letters: 10
latest_element:
  # Must be one of the options, and the games will use it and the previous 
  # ones.
  # Options: 'base', 'k', 's', 't', 'n', 'h', 'm', 'y', 'r', 'w', 'n', 'g',
  #          'z', 'd', 'b', 'p', 'ky', 'sh', 'ch', 'ny', 'hy', 'my', 'ry',
  #          'gy', 'j', 'by', 'py'
  hiragana: py
  # Must be one of the options, and the games will use it and the previous 
  # ones.
  # Options: 'base', 'k', 's', 't', 'n', 'h', 'm', 'y', 'r', 'w', 'n', 'g',
  #          'z', 'd', 'b', 'p', 'ky', 'sh', 'ch', 'ny', 'hy', 'my', 'ry',
  #          'gy', 'j', 'by', 'py'
  katakana: py
  # The school grade that is taught in according to the Joyo Kanji List,
  # ranges from 1 to 7, or 0 for none
  kanji: 7